# Artificial Neural Network

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Data Loading

In [2]:
churn = pd.read_csv(r"C:\Users\Kajal\Desktop\ssd\Desktop\ANN\datasets\Churn_Modelling.csv")
churn

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

# info

In [3]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


# describe

In [4]:
churn.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

# check null values

In [5]:
churn.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [6]:
churn.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

# LabelEncoding (Convert data string to numeric)

In [7]:
from sklearn.preprocessing import LabelEncoder
L1 = LabelEncoder()
churn["Geography"]=L1.fit_transform(churn["Geography"])
churn["Gender"]=L1.fit_transform(churn["Gender"])
churn["Surname"]=L1.fit_transform(churn["Surname"])
churn

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0             1    15634602     1115          619          0       0   42   
1             2    15647311     1177          608          2       0   41   
2             3    15619304     2040          502          0       0   42   
3             4    15701354      289          699          0       0   39   
4             5    15737888     1822          850          2       0   43   
...         ...         ...      ...          ...        ...     ...  ...   
9995       9996    15606229     1999          771          0       1   39   
9996       9997    15569892     1336          516          0       1   35   
9997       9998    15584532     1570          709          0       0   36   
9998       9999    15682355     2345          772          1       1   42   
9999      10000    15628319     2751          792          0       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

# Data slicing (dependent & independent variables)

In [8]:
x = churn.iloc[:,0:13].values
x

array([[1.0000000e+00, 1.5634602e+07, 1.1150000e+03, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.0000000e+00, 1.5647311e+07, 1.1770000e+03, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [3.0000000e+00, 1.5619304e+07, 2.0400000e+03, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [9.9980000e+03, 1.5584532e+07, 1.5700000e+03, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [9.9990000e+03, 1.5682355e+07, 2.3450000e+03, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+04, 1.5628319e+07, 2.7510000e+03, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [9]:
y = churn.iloc[:,-1].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

# Model train_test_split

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
print(X_train.shape,X_test.shape,y_test.shape,y_train.shape)

(8000, 13) (2000, 13) (2000,) (8000,)


# Algorithm define

In [13]:
ann = tf.keras.models.Sequential()

# input layer

In [14]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

# first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

# second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))

# output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# compilation

In [18]:
ann.compile(optimizer ='adam', loss='binary_crossentropy',metrics=['accuracy'])

In [19]:
ann.fit(X_train,y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5865 - accuracy: 0.7369
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4632 - accuracy: 0.7965
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4461 - accuracy: 0.8001
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4365 - accuracy: 0.8069
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4293 - accuracy: 0.8145
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4233 - accuracy: 0.8206
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4163 - accuracy: 0.8248
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4082 - accuracy: 0.8314
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3986 - accuracy: 0.8340
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3892 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3449 - accuracy: 0.8581
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3452 - accuracy: 0.8587
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3452 - accuracy: 0.8597
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3446 - accuracy: 0.8589
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3448 - accuracy: 0.8586
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3444 - accuracy: 0.8594
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3443 - accuracy: 0.8584
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3441 - accuracy: 0.8584
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3443 - accuracy: 0.8570
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3440 - accuracy: 

# prediction

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# accuracy score

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac = accuracy_score(y_pred,y_test)*100
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)

In [22]:
print(ac)

86.25


In [23]:
print(cm)

[[1555  235]
 [  40  170]]


In [24]:
print(cr)

              precision    recall  f1-score   support

       False       0.97      0.87      0.92      1790
        True       0.42      0.81      0.55       210

    accuracy                           0.86      2000
   macro avg       0.70      0.84      0.74      2000
weighted avg       0.92      0.86      0.88      2000

