# Artificial Neural Network

1. Artificial Neural Network is subset of Machine Learning
2. Artificial Neural Network is Multilayer,Fully connected neural nets that contains Input Layer, Multiple Hidden Layers,          Activation Functions, Output Layers

Activation Functions :
1. Relu
2. Sigmoid
3. Softmax
4. Threshold
5. Hyprebolic Tangent

# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

# Data Loading

In [2]:
dia = pd.read_csv(r"C:\Users\Kajal\Desktop\ssd\Desktop\dataset work November\datasets\diabetes.csv")

In [3]:
dia

Person  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0         6      148             72             35        0  33.6   
1         1       85             66             29        0  26.6   
2         8      183             64              0        0  23.3   
3         1       89             66             23       94  28.1   
4         0      137             40             35      168  43.1   
..      ...      ...            ...            ...      ...   ...   
763      10      101             76             48      180  32.9   
764       2      122             70             27        0  36.8   
765       5      121             72             23      112  26.2   
766       1      126             60              0        0  30.1   
767       1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

# info

In [4]:
dia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Person                    768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


# describe

In [5]:
dia.describe()

Person     Glucose  BloodPressure  SkinThickness     Insulin  \
count  768.000000  768.000000     768.000000     768.000000  768.000000   
mean     3.845052  120.894531      69.105469      20.536458   79.799479   
std      3.369578   31.972618      19.355807      15.952218  115.244002   
min      0.000000    0.000000       0.000000       0.000000    0.000000   
25%      1.000000   99.000000      62.000000       0.000000    0.000000   
50%      3.000000  117.000000      72.000000      23.000000   30.500000   
75%      6.000000  140.250000      80.000000      32.000000  127.250000   
max     17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

# Checking null values

In [6]:
dia.isnull().any()

Person                      False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool

In [7]:
dia.isnull().sum()

Person                      0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
dia["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

# Data slice into two variables (Dependent & Independent)

In [9]:
x = dia.iloc[:,0:8].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
y = dia.iloc[:,-1].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

# Use imbalance technique (Over Sampling) because the data is imbalanced

In [11]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
x_data,y_data = ros.fit_resample(x,y)

In [12]:
print(x_data.shape)
print(y_data.shape)

(1000, 8)
(1000,)


# Check data is balanced or not using Counter

In [13]:
from collections import Counter
print("This is Original{}".format(Counter(y)))

print("This is resample{}".format(Counter(y_data)))

This is OriginalCounter({0: 500, 1: 268})
This is resampleCounter({1: 500, 0: 500})


# Model train_test_split

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data, test_size=0.2, random_state=0)

In [15]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(800, 8) (200, 8) (800,) (200,)


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

# Algorithm define

In [17]:
ann = tf.keras.models.Sequential()

# Input Layer

In [18]:
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

# first hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

# second hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=5,activation='relu'))

# output layer

In [21]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Compilation

In [22]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [23]:
ann.fit(x_train,y_train, batch_size=32, epochs=100)

Epoch 1/100
25/25 [==============================] - 1s 4ms/step - loss: 0.6727 - accuracy: 0.5725
Epoch 2/100
25/25 [==============================] - 0s 5ms/step - loss: 0.6581 - accuracy: 0.6363
Epoch 3/100
25/25 [==============================] - 0s 6ms/step - loss: 0.6442 - accuracy: 0.6575
Epoch 4/100
25/25 [==============================] - 0s 6ms/step - loss: 0.6299 - accuracy: 0.6938
Epoch 5/100
25/25 [==============================] - 0s 5ms/step - loss: 0.6135 - accuracy: 0.7000
Epoch 6/100
25/25 [==============================] - 0s 5ms/step - loss: 0.5988 - accuracy: 0.7025
Epoch 7/100
25/25 [==============================] - 0s 4ms/step - loss: 0.5842 - accuracy: 0.7175
Epoch 8/100
25/25 [==============================] - 0s 4ms/step - loss: 0.5697 - accuracy: 0.7188
Epoch 9/100
25/25 [==============================] - 0s 4ms/step - loss: 0.5568 - accuracy: 0.7250
Epoch 10/100
25/25 [==============================] - 0s 5ms/step - loss: 0.5462 - accuracy: 0.7312
Epoch 11/

Epoch 83/100
25/25 [==============================] - 0s 5ms/step - loss: 0.4793 - accuracy: 0.7638
Epoch 84/100
25/25 [==============================] - 0s 5ms/step - loss: 0.4790 - accuracy: 0.7700
Epoch 85/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4786 - accuracy: 0.7675
Epoch 86/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4788 - accuracy: 0.7638
Epoch 87/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4783 - accuracy: 0.7650
Epoch 88/100
25/25 [==============================] - 0s 5ms/step - loss: 0.4782 - accuracy: 0.7638
Epoch 89/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4778 - accuracy: 0.7650
Epoch 90/100
25/25 [==============================] - 0s 5ms/step - loss: 0.4775 - accuracy: 0.7650
Epoch 91/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4777 - accuracy: 0.7638
Epoch 92/100
25/25 [==============================] - 0s 4ms/step - loss: 0.4774 - accuracy: 0.7638


# Prediction

In [24]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]

# Accuracy_score, Confusion_matrix, Classification_report

In [25]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac = accuracy_score(y_pred,y_test)*100
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)

In [26]:
print(ac)

80.5


In [27]:
print(cm)

[[82 16]
 [23 79]]


In [28]:
print(cr)

              precision    recall  f1-score   support

       False       0.78      0.84      0.81        98
        True       0.83      0.77      0.80       102

    accuracy                           0.81       200
   macro avg       0.81      0.81      0.80       200
weighted avg       0.81      0.81      0.80       200

