In [1]:
import numpy as np
import pandas as pd

# Data Loading

In [2]:
iris = pd.read_csv(r"C:\Users\Kajal\Desktop\ssd\Desktop\dataset work November\datasets\Iris.csv")
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

# Data Preprocessing

# 1. info

In [3]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


# 2. Describe

In [4]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

# 3. Checking null values

In [5]:
iris.isnull().any()

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [6]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

# Label Encoding 

In [7]:
from sklearn.preprocessing import LabelEncoder
L1 = LabelEncoder()
iris["Species"]=L1.fit_transform(iris["Species"])
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [8]:
iris["Species"].value_counts()

0    50
1    50
2    50
Name: Species, dtype: int64

# Data slice into two variables (Dependent & Independent)

In [9]:
x=iris.iloc[:,0:5]
x

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [10]:
y=iris.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

# Model train_test_split

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [12]:
x_train.values

array([[1.38e+02, 6.40e+00, 3.10e+00, 5.50e+00, 1.80e+00],
       [8.50e+01, 5.40e+00, 3.00e+00, 4.50e+00, 1.50e+00],
       [2.80e+01, 5.20e+00, 3.50e+00, 1.50e+00, 2.00e-01],
       [1.28e+02, 6.10e+00, 3.00e+00, 4.90e+00, 1.80e+00],
       [1.33e+02, 6.40e+00, 2.80e+00, 5.60e+00, 2.20e+00],
       [6.00e+01, 5.20e+00, 2.70e+00, 3.90e+00, 1.40e+00],
       [1.90e+01, 5.70e+00, 3.80e+00, 1.70e+00, 3.00e-01],
       [8.40e+01, 6.00e+00, 2.70e+00, 5.10e+00, 1.60e+00],
       [6.20e+01, 5.90e+00, 3.00e+00, 4.20e+00, 1.50e+00],
       [9.30e+01, 5.80e+00, 2.60e+00, 4.00e+00, 1.20e+00],
       [1.13e+02, 6.80e+00, 3.00e+00, 5.50e+00, 2.10e+00],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [1.42e+02, 6.90e+00, 3.10e+00, 5.10e+00, 2.30e+00],
       [4.40e+01, 5.00e+00, 3.50e+00, 1.60e+00, 6.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [6.10e+01, 5.00e+00, 2.00e+00, 3.50e+00, 1.00e+00],
       [1.17e+02, 6.50e+00, 3.00e+00, 5.50e+00, 1.80e+00

In [13]:
x_test.values

array([[1.15e+02, 5.80e+00, 2.80e+00, 5.10e+00, 2.40e+00],
       [6.30e+01, 6.00e+00, 2.20e+00, 4.00e+00, 1.00e+00],
       [3.40e+01, 5.50e+00, 4.20e+00, 1.40e+00, 2.00e-01],
       [1.08e+02, 7.30e+00, 2.90e+00, 6.30e+00, 1.80e+00],
       [8.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [1.01e+02, 6.30e+00, 3.30e+00, 6.00e+00, 2.50e+00],
       [4.10e+01, 5.00e+00, 3.50e+00, 1.30e+00, 3.00e-01],
       [8.70e+01, 6.70e+00, 3.10e+00, 4.70e+00, 1.50e+00],
       [7.70e+01, 6.80e+00, 2.80e+00, 4.80e+00, 1.40e+00],
       [7.20e+01, 6.10e+00, 2.80e+00, 4.00e+00, 1.30e+00],
       [1.35e+02, 6.10e+00, 2.60e+00, 5.60e+00, 1.40e+00],
       [5.20e+01, 6.40e+00, 3.20e+00, 4.50e+00, 1.50e+00],
       [7.40e+01, 6.10e+00, 2.80e+00, 4.70e+00, 1.20e+00],
       [5.50e+01, 6.50e+00, 2.80e+00, 4.60e+00, 1.50e+00],
       [6.40e+01, 6.10e+00, 2.90e+00, 4.70e+00, 1.40e+00],
       [3.80e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [7.90e+01, 6.00e+00, 2.90e+00, 4.50e+00, 1.50e+00

In [14]:
y_train.values

array([2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [15]:
y_test.values

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

# Algorithm define (KNN)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn.fit(x_train,y_train)

KNeighborsClassifier()

# Prediction

In [17]:
y_pred = knn.predict(x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

# Accuracy_score,Confusion_matrix,Classification_report

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac = accuracy_score(y_pred,y_test)*100
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)
print(ac)
print("************************************")

print(cm)
print("************************************")

print(cr)

100.0
************************************
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

